apiVersion: v1
kind: Service
metadata:
  name: dify-api
  labels:
    app: dify-api
spec:
  selector:
    app: dify-api
  ports:
    - name: http
      port: 80
      targetPort: 5001
  type: ClusterIP
